import os
import time

import psycopg
from dotenv import load_dotenv

load_dotenv()


def init_db():
    for attempt in range(10):  # 10 tentatives max
        try:
            conn = psycopg.connect(
                f"dbname={os.getenv('POSTGRES_DB')} user={os.getenv('POSTGRES_USER')} password={os.getenv('POSTGRES_PASSWORD')} host={os.getenv('POSTGRES_HOST')}"
            )
            with conn:
                with conn.cursor() as cur:
                    cur.execute("""
                        CREATE TABLE IF NOT EXISTS "users" (
                          "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          "name" varchar,
                          "surname" varchar,
                          "email" varchar,
                          "password" varchar,
                          "verified" bool DEFAULT false,
                          "last_password_change" timestamp DEFAULT (now()),
                          "created_at" timestamp
                        );
                        CREATE TABLE IF NOT EXISTS "connections" (
                          "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          "user_id" integer,
                          "username" varchar,
                          "password" varchar,
                          "token" varchar,
                          "type" varchar,
                          "account_id" varchar,
                          "region" varchar
                        );
                        CREATE TABLE IF NOT EXISTS "remember_tokens" (
                          "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          "user_id" INTEGER,
                          "token_hash" varchar NOT NULL,
                          "issued_at" TIMESTAMP NOT NULL DEFAULT NOW(),
                          "expires_at" TIMESTAMP NOT NULL,
                          "user_agent" varchar,
                          "ip_address" varchar
                        );
                        ALTER TABLE "connections" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
                        ALTER TABLE "remember_tokens" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
                    """)
            print("✅ Successfully connected to PostgreSQL DB.")
            return conn
        except psycopg.OperationalError as e:
            print(
                f"⏳ Connection to PostgreSQL: attempt {attempt + 1}/10 : Not ready ({e})")
            time.sleep(2)

    raise Exception(
        "❌ Impossible de se connecter à PostgreSQL après plusieurs tentatives"
    )


def get_conn():
    return psycopg.connect(
        f"dbname={os.getenv('POSTGRES_DB')} user={os.getenv('POSTGRES_USER')} password={os.getenv('POSTGRES_PASSWORD')} host={os.getenv('POSTGRES_HOST')}"
    )
